import { fileURLToPath } from 'node:url';

const BUILTIN_SITE_IDS = [
  'bilibili',
  'hackernews',
  'arxiv',
  '12306',
  '1point3acres',
  'coingecko',
  'wikipedia',
  'npm',
  'openalex',
  'endoflife',
  'archive',
  'apple-podcasts',
  'bbc',
  'binance',
  'autohome',
  'bluesky',
  'crates',
  'dblp',
  'openreview',
  'defillama',
  'goproxy',
  'dockerhub',
  'osv',
  'packagist',
  'rubygems',
  'pypi',
  'nuget',
  'devto',
  'oeis',
  'flathub',
  'flomo',
  'nvd',
  'openfda',
  'wttr',
  'semanticscholar',
  'rfc',
  'tvmaze',
  'wikidata',
  'pubmed',
  'dictionary',
  'github-trending',
  'homebrew',
  'lobsters',
  'maven',
  'lichess',
  'juejin',
  'mdn',
  'lesswrong',
  'stackoverflow',
  'steam',
  'duckduckgo',
  'google',
  'medium',
  'hf',
  'bloomberg',
  'chess',
  'ths',
  '36kr',
  'v2ex',
  'nowcoder',
  'linux-do',
  'zsxq',
  'xueqiu',
  'reddit',
  'pixiv',
  'boss',
  'zhihu',
  'uisdc',
  'barchart',
  'linkedin-learning',
  'yahoo-finance',
  'huodongxing',
  'weibo',
  'quark',
  'uiverse',
  'reuters',
  'tieba',
  'douban',
  'hupu',
  'google-scholar',
  'github',
  'booking',
  'wanfang',
  'powerchina',
  'maimai',
  'instagram',
  'producthunt',
  'yollomi',
  'ctrip',
  'toutiao',
  'sinafinance',
  'eastmoney',
  'dongchedi',
  'guazi',
  'substack',
  'sinablog',
  'trip',
  'weread',
  'paperreview',
] as const;

export type BuiltinSiteId = (typeof BUILTIN_SITE_IDS)[number];

export function builtinSiteIds(): BuiltinSiteId[] {
  return [...BUILTIN_SITE_IDS];
}

export function builtinSiteSources(): Record<BuiltinSiteId, string> {
  return Object.fromEntries(
    BUILTIN_SITE_IDS.map(id => [id, fileURLToPath(new URL(`./adapters/${id}`, import.meta.url))]),
  ) as Record<BuiltinSiteId, string>;
}
