import { fileURLToPath } from 'node:url';

const BUILTIN_SITE_IDS = [
  'bilibili',
  'hackernews',
  'arxiv',
  '12306',
  '1point3acres',
  'coingecko',
  'wikipedia',
  'npm',
  'openalex',
  'endoflife',
  'archive',
  'apple-podcasts',
  'bbc',
  'binance',
  'autohome',
  'bluesky',
  'crates',
  'dblp',
  'openreview',
  'defillama',
  'goproxy',
  'dockerhub',
  'osv',
  'packagist',
  'rubygems',
  'pypi',
  'nuget',
  'devto',
  'oeis',
  'flathub',
  'flomo',
  'nvd',
  'openfda',
  'wttr',
  'semanticscholar',
  'rfc',
  'tvmaze',
  'wikidata',
  'pubmed',
  'dictionary',
  'github-trending',
  'homebrew',
  'lobsters',
  'maven',
  'lichess',
  'juejin',
  'mdn',
  'lesswrong',
  'stackoverflow',
  'steam',
  'duckduckgo',
  'google',
  'medium',
  'hf',
  'bloomberg',
  'chess',
  'ths',
  '36kr',
  'v2ex',
  'nowcoder',
  'linux-do',
  'zsxq',
  'xueqiu',
  'reddit',
  'pixiv',
  'boss',
  'zhihu',
  'uisdc',
  'barchart',
  'linkedin-learning',
  'yahoo-finance',
  'huodongxing',
  'weibo',
  'quark',
  'uiverse',
  'reuters',
  'tieba',
  'douban',
  'hupu',
  'google-scholar',
  'github',
  'booking',
  'wanfang',
  'powerchina',
  'maimai',
  'instagram',
  'producthunt',
  'yollomi',
  'ctrip',
  'toutiao',
  'sinafinance',
  'eastmoney',
  'dongchedi',
  'guazi',
  'substack',
  'sinablog',
  'trip',
  'weread',
  'paperreview',
] as const;

export type BuiltinSiteId = (typeof BUILTIN_SITE_IDS)[number];

export function builtinSiteIds(): BuiltinSiteId[] {
  return [...BUILTIN_SITE_IDS];
}

export function builtinSiteSources(): Record<BuiltinSiteId, string> {
  return {
    bilibili: fileURLToPath(new URL('./adapters/bilibili', import.meta.url)),
    hackernews: fileURLToPath(new URL('./adapters/hackernews', import.meta.url)),
    arxiv: fileURLToPath(new URL('./adapters/arxiv', import.meta.url)),
    '12306': fileURLToPath(new URL('./adapters/12306', import.meta.url)),
    '1point3acres': fileURLToPath(new URL('./adapters/1point3acres', import.meta.url)),
    coingecko: fileURLToPath(new URL('./adapters/coingecko', import.meta.url)),
    wikipedia: fileURLToPath(new URL('./adapters/wikipedia', import.meta.url)),
    npm: fileURLToPath(new URL('./adapters/npm', import.meta.url)),
    openalex: fileURLToPath(new URL('./adapters/openalex', import.meta.url)),
    endoflife: fileURLToPath(new URL('./adapters/endoflife', import.meta.url)),
    archive: fileURLToPath(new URL('./adapters/archive', import.meta.url)),
    'apple-podcasts': fileURLToPath(new URL('./adapters/apple-podcasts', import.meta.url)),
    bbc: fileURLToPath(new URL('./adapters/bbc', import.meta.url)),
    binance: fileURLToPath(new URL('./adapters/binance', import.meta.url)),
    autohome: fileURLToPath(new URL('./adapters/autohome', import.meta.url)),
    bluesky: fileURLToPath(new URL('./adapters/bluesky', import.meta.url)),
    crates: fileURLToPath(new URL('./adapters/crates', import.meta.url)),
    dblp: fileURLToPath(new URL('./adapters/dblp', import.meta.url)),
    openreview: fileURLToPath(new URL('./adapters/openreview', import.meta.url)),
    defillama: fileURLToPath(new URL('./adapters/defillama', import.meta.url)),
    goproxy: fileURLToPath(new URL('./adapters/goproxy', import.meta.url)),
    dockerhub: fileURLToPath(new URL('./adapters/dockerhub', import.meta.url)),
    osv: fileURLToPath(new URL('./adapters/osv', import.meta.url)),
    packagist: fileURLToPath(new URL('./adapters/packagist', import.meta.url)),
    rubygems: fileURLToPath(new URL('./adapters/rubygems', import.meta.url)),
    pypi: fileURLToPath(new URL('./adapters/pypi', import.meta.url)),
    nuget: fileURLToPath(new URL('./adapters/nuget', import.meta.url)),
    devto: fileURLToPath(new URL('./adapters/devto', import.meta.url)),
    oeis: fileURLToPath(new URL('./adapters/oeis', import.meta.url)),
    flathub: fileURLToPath(new URL('./adapters/flathub', import.meta.url)),
    flomo: fileURLToPath(new URL('./adapters/flomo', import.meta.url)),
    nvd: fileURLToPath(new URL('./adapters/nvd', import.meta.url)),
    openfda: fileURLToPath(new URL('./adapters/openfda', import.meta.url)),
    wttr: fileURLToPath(new URL('./adapters/wttr', import.meta.url)),
    semanticscholar: fileURLToPath(new URL('./adapters/semanticscholar', import.meta.url)),
    rfc: fileURLToPath(new URL('./adapters/rfc', import.meta.url)),
    tvmaze: fileURLToPath(new URL('./adapters/tvmaze', import.meta.url)),
    wikidata: fileURLToPath(new URL('./adapters/wikidata', import.meta.url)),
    pubmed: fileURLToPath(new URL('./adapters/pubmed', import.meta.url)),
    dictionary: fileURLToPath(new URL('./adapters/dictionary', import.meta.url)),
    'github-trending': fileURLToPath(new URL('./adapters/github-trending', import.meta.url)),
    homebrew: fileURLToPath(new URL('./adapters/homebrew', import.meta.url)),
    lobsters: fileURLToPath(new URL('./adapters/lobsters', import.meta.url)),
    maven: fileURLToPath(new URL('./adapters/maven', import.meta.url)),
    lichess: fileURLToPath(new URL('./adapters/lichess', import.meta.url)),
    juejin: fileURLToPath(new URL('./adapters/juejin', import.meta.url)),
    mdn: fileURLToPath(new URL('./adapters/mdn', import.meta.url)),
    lesswrong: fileURLToPath(new URL('./adapters/lesswrong', import.meta.url)),
    stackoverflow: fileURLToPath(new URL('./adapters/stackoverflow', import.meta.url)),
    steam: fileURLToPath(new URL('./adapters/steam', import.meta.url)),
    duckduckgo: fileURLToPath(new URL('./adapters/duckduckgo', import.meta.url)),
    google: fileURLToPath(new URL('./adapters/google', import.meta.url)),
    medium: fileURLToPath(new URL('./adapters/medium', import.meta.url)),
    hf: fileURLToPath(new URL('./adapters/hf', import.meta.url)),
    bloomberg: fileURLToPath(new URL('./adapters/bloomberg', import.meta.url)),
    chess: fileURLToPath(new URL('./adapters/chess', import.meta.url)),
    ths: fileURLToPath(new URL('./adapters/ths', import.meta.url)),
    '36kr': fileURLToPath(new URL('./adapters/36kr', import.meta.url)),
    v2ex: fileURLToPath(new URL('./adapters/v2ex', import.meta.url)),
    nowcoder: fileURLToPath(new URL('./adapters/nowcoder', import.meta.url)),
    'linux-do': fileURLToPath(new URL('./adapters/linux-do', import.meta.url)),
    zsxq: fileURLToPath(new URL('./adapters/zsxq', import.meta.url)),
    xueqiu: fileURLToPath(new URL('./adapters/xueqiu', import.meta.url)),
    reddit: fileURLToPath(new URL('./adapters/reddit', import.meta.url)),
    pixiv: fileURLToPath(new URL('./adapters/pixiv', import.meta.url)),
    boss: fileURLToPath(new URL('./adapters/boss', import.meta.url)),
    zhihu: fileURLToPath(new URL('./adapters/zhihu', import.meta.url)),
    uisdc: fileURLToPath(new URL('./adapters/uisdc', import.meta.url)),
    barchart: fileURLToPath(new URL('./adapters/barchart', import.meta.url)),
    'linkedin-learning': fileURLToPath(new URL('./adapters/linkedin-learning', import.meta.url)),
    'yahoo-finance': fileURLToPath(new URL('./adapters/yahoo-finance', import.meta.url)),
    huodongxing: fileURLToPath(new URL('./adapters/huodongxing', import.meta.url)),
    weibo: fileURLToPath(new URL('./adapters/weibo', import.meta.url)),
    quark: fileURLToPath(new URL('./adapters/quark', import.meta.url)),
    uiverse: fileURLToPath(new URL('./adapters/uiverse', import.meta.url)),
    reuters: fileURLToPath(new URL('./adapters/reuters', import.meta.url)),
    tieba: fileURLToPath(new URL('./adapters/tieba', import.meta.url)),
    douban: fileURLToPath(new URL('./adapters/douban', import.meta.url)),
    hupu: fileURLToPath(new URL('./adapters/hupu', import.meta.url)),
    'google-scholar': fileURLToPath(new URL('./adapters/google-scholar', import.meta.url)),
    github: fileURLToPath(new URL('./adapters/github', import.meta.url)),
    booking: fileURLToPath(new URL('./adapters/booking', import.meta.url)),
    wanfang: fileURLToPath(new URL('./adapters/wanfang', import.meta.url)),
    powerchina: fileURLToPath(new URL('./adapters/powerchina', import.meta.url)),
    maimai: fileURLToPath(new URL('./adapters/maimai', import.meta.url)),
    instagram: fileURLToPath(new URL('./adapters/instagram', import.meta.url)),
    producthunt: fileURLToPath(new URL('./adapters/producthunt', import.meta.url)),
    yollomi: fileURLToPath(new URL('./adapters/yollomi', import.meta.url)),
    ctrip: fileURLToPath(new URL('./adapters/ctrip', import.meta.url)),
    toutiao: fileURLToPath(new URL('./adapters/toutiao', import.meta.url)),
    sinafinance: fileURLToPath(new URL('./adapters/sinafinance', import.meta.url)),
    eastmoney: fileURLToPath(new URL('./adapters/eastmoney', import.meta.url)),
    dongchedi: fileURLToPath(new URL('./adapters/dongchedi', import.meta.url)),
    guazi: fileURLToPath(new URL('./adapters/guazi', import.meta.url)),
    substack: fileURLToPath(new URL('./adapters/substack', import.meta.url)),
    sinablog: fileURLToPath(new URL('./adapters/sinablog', import.meta.url)),
    trip: fileURLToPath(new URL('./adapters/trip', import.meta.url)),
    weread: fileURLToPath(new URL('./adapters/weread', import.meta.url)),
    paperreview: fileURLToPath(new URL('./adapters/paperreview', import.meta.url)),
  };
}
