import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSite } from '@panerelay/site-kit';

const packageDirectory = dirname(fileURLToPath(import.meta.url));
const catalogPackage = JSON.parse(await readFile(join(packageDirectory, 'package.json'), 'utf8'));
for (const siteId of [
  'bilibili',
  'hackernews',
  'arxiv',
  '12306',
  '1point3acres',
  'coingecko',
  'wikipedia',
  'npm',
  'openalex',
  'endoflife',
  'archive',
  'apple-podcasts',
  'bbc',
  'binance',
  'autohome',
  'bluesky',
  'crates',
  'dblp',
  'openreview',
  'defillama',
  'goproxy',
  'dockerhub',
  'osv',
  'packagist',
  'rubygems',
  'pypi',
  'nuget',
  'devto',
  'oeis',
  'flathub',
  'flomo',
  'nvd',
  'openfda',
  'wttr',
  'semanticscholar',
  'rfc',
  'tvmaze',
  'wikidata',
  'pubmed',
  'dictionary',
  'github-trending',
  'homebrew',
  'lobsters',
  'maven',
  'lichess',
  'juejin',
  'mdn',
  'lesswrong',
  'stackoverflow',
  'steam',
  'duckduckgo',
  'google',
  'medium',
  'hf',
  'bloomberg',
  'chess',
  'ths',
  '36kr',
  'v2ex',
  'nowcoder',
  'linux-do',
  'zsxq',
  'xueqiu',
  'reddit',
  'pixiv',
  'boss',
  'zhihu',
  'uisdc',
  'barchart',
  'linkedin-learning',
  'yahoo-finance',
  'huodongxing',
  'weibo',
  'quark',
  'uiverse',
  'reuters',
  'tieba',
  'douban',
  'hupu',
  'google-scholar',
  'github',
  'booking',
  'wanfang',
  'powerchina',
  'maimai',
  'instagram',
  'producthunt',
  'yollomi',
  'ctrip',
  'toutiao',
  'sinafinance',
  'eastmoney',
  'dongchedi',
  'guazi',
  'substack',
  'sinablog',
  'trip',
  'weread',
  'paperreview',
]) {
  await buildSite(join(packageDirectory, 'src', siteId), {
    outDirectory: join(packageDirectory, 'dist', 'adapters', siteId),
    version: catalogPackage.version,
  });
}
